In [18]:
import re

In [19]:
input = "hello@ my name is #yash"
cleaned_text= re.sub(r"[^a-zA-z0-9]"," ",input)
cleaned_text

'hello  my name is  yash'

In [20]:
input = "hello@my name is #yash12638"
cleaned_text= re.sub(r"[^a-zA-z0-9]"," ",input)
cleaned_text

'hello my name is  yash12638'

In [21]:
input = "hello@my name is #yash12638"
cleaned_text= re.sub(r"[^a-zA-Z]"," ",input)
cleaned_text

'hello my name is  yash     '

In [22]:
! pip install contractions
import contractions
text ="i'm going"
expanded_text= contractions.fix(text)
print(expanded_text)


i am going


In [23]:
! pip install nltk

In [24]:
import nltk

In [25]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [29]:
input = "hello@ my name is #himanshu"
tokens= nltk.word_tokenize(input)#convert into tokrns like "hello"
print(tokens)

clean_text =[token for token in tokens if token.isalnum()]#
cleaned_text=' '.join(clean_text)
print(cleaned_text)

['hello', '@', 'my', 'name', 'is', '#', 'himanshu']
hello my name is himanshu


In [27]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.


True

In [ ]:
sentence = "Ram is https://pypi.org/project/nltk/shayam"## removve html
import re
re.sub(r"<.*?>","")

In [31]:
chat_word_dict = {
    "u": "you",
    "r": "are",
    "b4": "before",
    "gr8": "great",
    "l8r": "later",
    "idk": "I don’t know",
    "btw": "by the way",
    "imo": "in my opinion",
    "ttyl": "talk to you later",
    "brb": "be right back",
    "wanna": "want to",
    "gonna": "going to",
    "lemme": "let me",
    "dunno": "don’t know",
    "thx": "thanks",
    "pls": "please",
    "ppl": "people",
    "smh": "shaking my head",
    "tbh": "to be honest",
    "omg": "oh my god",
    "lol": "laugh out loud",
    "rofl": "rolling on the floor laughing",
    "afk": "away from keyboard",
    "np": "no problem",
    "gtg": "got to go",
    "jk": "just kidding",
    "hbu": "how about you",
    "ily": "I love you",
    "ttys": "talk to you soon"
}

In [35]:
chat_text = "omg idk what  u r taking about "
def normalize_text(chat_text):
    words =chat_text.split()
    normalized_words=[chat_word_dict.get(word.lower(), word) for word in words]
    return" ".join(normalized_words)


In [36]:
normalized_text=normalize_text(chat_text = "omg idk what ur talking about lol")

In [37]:
normalized_text

'oh my god I don’t know what ur talking about laugh out loud'

In [38]:
! pip install textblob

   ---------------------------------------- 0.0/624.3 kB ? eta -:--:--
   ---------------------------------------- 624.3/624.3 kB 7.7 MB/s eta 0:00:00


In [42]:
from textblob import TextBlob
text = "mye nameee is yash"
spelling_correct= TextBlob(text).correct()
print(spelling_correct)

my name is wash


In [45]:
# Speech to text(stt)
! pip install SpeechRecognition
! pip install pyaudio

In [47]:
import speech_recognition as sr
recognizer = sr.Recognizer()
with sr.Microphone() as source:
    print("speak now")
    audio =recognizer.listen(source)
try:
    text = recognizer.recognize_google(audio)
    print("you said", text)
except:
    print("sorry could not recognize your voice")

speak now
you said hello my name is Yash Sharma


In [49]:
! pip install gtts
from gtts import gTTS
import os
text = "Hello welcome to my home "
tts = gTTS(text = text , lang="en")
tts.save("welcome.mp3")
os.system("welcome.mp3")

0

In [1]:
import pandas as pd
import numpy as np

In [2]:
text = {"text":["people watch Aiyug","Aiyug watch Aiyug","People write comment","Aiyug write comment"],"Output":[1,1,0,0]}

In [3]:
text =pd.DataFrame(text)

In [4]:
text

text  Output
0    people watch Aiyug       1
1     Aiyug watch Aiyug       1
2  People write comment       0
3   Aiyug write comment       0

In [5]:
from sklearn .feature_extraction.text import CountVectorizer

In [6]:
cv =CountVectorizer(lowercase=True, stop_words='english', binary=True)


In [7]:
bow =cv.fit_transform(text['text'])

In [8]:
cv.vocabulary_

{'people': 2, 'watch': 3, 'aiyug': 0, 'write': 4, 'comment': 1}

In [9]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[1 0 1 1 0]]
[[1 0 0 1 0]]
[[0 1 1 0 1]]
[[1 1 0 0 1]]


In [10]:
! pip install scikit-learn

In [12]:
from nltk.util import ngrams
from nltk.tokenize import word_tokenize

text = "I love natural language processing"
tokens = word_tokenize(text)
n =2

bigrams =list(ngrams(tokens,n))
print("bigrams:-",bigrams)

bigrams:- [('I', 'love'), ('love', 'natural'), ('natural', 'language'), ('language', 'processing')]


TF-IDF

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer
text = ["i love natural language processing", "i love machine learning", "i love deep learning"]
vectorizer=TfidfVectorizer()
tfidf_matrix=vectorizer.fit_transform(text)
#print(tfidf_matrix.toarray())
feature_names=vectorizer.get_feature_names_out()


for doc_index, doc in enumerate(tfidf_matrix.toarray()):
    print("document:-", doc_index+1)
    for word_index, score in enumerate (doc):
        if score> 0:
            print(f"{feature_names [word_index]}: {score:.4f}")

document:- 1
language: 0.5465
love: 0.3227
natural: 0.5465
processing: 0.5465
document:- 2
learning: 0.5478
love: 0.4254
machine: 0.7203
document:- 3
deep: 0.7203
learning: 0.5478
love: 0.4254


In [15]:
vectorizer.get_feature_names_out()

array(['deep', 'language', 'learning', 'love', 'machine', 'natural',
       'processing'], dtype=object)

Part of speech tagging

In [17]:
! pip install spacy

   ---------------------------------------- 0.0/14.9 MB ? eta -:--:--
   -- ------------------------------------- 0.8/14.9 MB 4.2 MB/s eta 0:00:04
   ---- ----------------------------------- 1.8/14.9 MB 4.8 MB/s eta 0:00:03
   ------- -------------------------------- 2.9/14.9 MB 4.7 MB/s eta 0:00:03
   --------- ------------------------------ 3.4/14.9 MB 4.5 MB/s eta 0:00:03
   ----------- ---------------------------- 4.2/14.9 MB 4.3 MB/s eta 0:00:03
   -------------- ------------------------- 5.2/14.9 MB 4.3 MB/s eta 0:00:03
   ----------------- ---------------------- 6.6/14.9 MB 4.6 MB/s eta 0:00:02
   --------------------- ------------------ 7.9/14.9 MB 4.8 MB/s eta 0:00:02
   ------------------------- -------------- 9.4/14.9 MB 5.1 MB/s eta 0:00:02
   ---------------------------- ----------- 10.7/14.9 MB 5.2 MB/s eta 0:00:01
   --------------------------------- ------ 12.6/14.9 MB 5.6 MB/s eta 0:00:01
   ------------------------------------- -- 14.2/14.9 MB 5.7 MB/s eta 0:00:01
   

In [18]:
import spacy

In [21]:
pos =spacy.load('en_core_web_sm')

In [22]:
doc =pos("i love natural langage processing")

In [23]:
doc.text

'i love natural langage processing'

In [24]:
doc[3].pos_

'NOUN'

In [25]:
from nltk.stem import PorterStemmer
st = PorterStemmer()
print(st.stem("loving"))

love


In [26]:
print(st.stem("loving"))
st.stem("loving")

love


'love'