In [3]:
import numpy as np

In [4]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [5]:
arr =np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [7]:
arr.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [14]:
np.random.randint(1,5,9)

array([2, 4, 1, 1, 2, 4, 1, 4, 1], dtype=int32)

In [15]:
np.random.randint(1,5,(5,2))

array([[4, 3],
       [1, 4],
       [1, 3],
       [2, 4],
       [2, 2]], dtype=int32)

In [16]:
np.random.random(10)

array([0.48552174, 0.35547416, 0.87307843, 0.74748364, 0.0555641 ,
       0.23301492, 0.34614044, 0.74842044, 0.97737423, 0.40744923])

In [17]:
arr=np.random.random((5,10))
arr.ndim

2

In [27]:
arr =np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [ ]:
arr=np.random.random((12,5))
arr.shape
arr.size
print("dimension of array",arr.ndim)
print("size of array",arr.size)
print("data type of array",arr.dtype)
print("shape of array",arr.shape)


dimension of array 2
size of array 60
data type of array float64
shape of array (12, 5)


In [28]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
arr.ravel()##both ravel and fatten do same as they converts 2d array to 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [30]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [31]:
arr.shape

(12, 5)

In [ ]:
arr.T.shape##swaping

(5, 12)

In [34]:
arr =np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [37]:
arr[0]=100
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [38]:
arr =np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [ ]:
arr[5,4]#first digit in bracket "5" is row while "4"is column

np.int64(29)

In [46]:
arr[0:5,1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [52]:
arr[7:8,4]==100 

array([False])

In [48]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [61]:
arr[11][4]

np.int64(59)

In [62]:
arr =np.array(np.arange(225).reshape(5,15,3))

In [63]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [64]:
arr[0][2:]

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [ ]:
arr[:,0:1,0:1
] ## :->table, 0(row se start):1(total rows to print)->rows, last 0:1->COLUMN

array([[[  4,   5],
        [  7,   8],
        [ 10,  11]],

       [[ 49,  50],
        [ 52,  53],
        [ 55,  56]],

       [[ 94,  95],
        [ 97,  98],
        [100, 101]],

       [[139, 140],
        [142, 143],
        [145, 146]],

       [[184, 185],
        [187, 188],
        [190, 191]]])

In [72]:
arr[2][3][1]

np.int64(100)

In [68]:
np.array([1,2,3,4,56])
arr.sort()

In [ ]:
#arr+2
##arr*arr
##arr/arr
##arr-arr
##arr+arr
##arr/2

array([[[    0,     1,     4],
        [    9,    16,    25],
        [   36,    49,    64],
        [   81,   100,   121],
        [  144,   169,   196],
        [  225,   256,   289],
        [  324,   361,   400],
        [  441,   484,   529],
        [  576,   625,   676],
        [  729,   784,   841],
        [  900,   961,  1024],
        [ 1089,  1156,  1225],
        [ 1296,  1369,  1444],
        [ 1521,  1600,  1681],
        [ 1764,  1849,  1936]],

       [[ 2025,  2116,  2209],
        [ 2304,  2401,  2500],
        [ 2601,  2704,  2809],
        [ 2916,  3025,  3136],
        [ 3249,  3364,  3481],
        [ 3600,  3721,  3844],
        [ 3969,  4096,  4225],
        [ 4356,  4489,  4624],
        [ 4761,  4900,  5041],
        [ 5184,  5329,  5476],
        [ 5625,  5776,  5929],
        [ 6084,  6241,  6400],
        [ 6561,  6724,  6889],
        [ 7056,  7225,  7396],
        [ 7569,  7744,  7921]],

       [[ 8100,  8281,  8464],
        [ 8649,  8836,  9025],
    